nofork: fix a bug uncovered by hush testsuite (forgotten fflush)
function                                             old     new   delta
run_nofork_applet                                    280     287      +7

Signed-off-by: Denys Vlasenko <vda.linux@googlemail.com>

diff --git a/shell/hush_test/run-all b/shell/hush_test/run-all
--- a/shell/hush_test/run-all
+++ b/shell/hush_test/run-all
@@ -80,7 +80,7 @@ do_test()
 		case $? in
 			0)  echo " ok";;
 			77) echo " skip (feature disabled)";;
-			*)  echo " fail"; tret=1;;
+			*)  echo " fail ($?)"; tret=1;;
 		esac
 	done
 	exit ${tret}
