Treat custom and applet scripts as applets
BusyBox has support for embedded shell scripts.  Two types can be
distinguished:  custom scripts and scripts implementing applets.

Custom scripts should be placed in the 'embed' directory at build
time.  They are given a default applet configuration and appear
as applets to the user but no further configuration is possible.

Applet scripts are integrated with the BusyBox build system and
are intended to be used to ship standard applets that just happen
to be implemented as scripts.  They can be configured at build time
and appear just like native applets.

Such scripts should be placed in the 'applets_sh' directory.  A stub
C program should be written to provide the usual applet configuration
details and placed in a suitable subsystem directory.  It may be
helpful to have a configuration option to enable any dependencies the
script requires:  see the 'nologin' applet for an example.

function                                             old     new   delta
scripted_main                                          -      41     +41
applet_names                                        2773    2781      +8
applet_main                                         1600    1604      +4
i2cdetect_main                                       672     674      +2
applet_suid                                          100     101      +1
applet_install_loc                                   200     201      +1
applet_flags                                         100     101      +1
packed_usage                                       33180   33179      -1
tryexec                                              159     152      -7
evalcommand                                         1661    1653      -8
script_names                                           9       -      -9
packed_scripts                                       123     114      -9
complete_cmd_dir_file                                826     811     -15
shellexec                                            271     254     -17
find_command                                        1007     990     -17
busybox_main                                         642     624     -18
run_applet_and_exit                                  100      78     -22
find_script_by_name                                   51       -     -51
------------------------------------------------------------------------------
(add/remove: 1/2 grow/shrink: 6/9 up/down: 58/-174)          Total: -116 bytes
   text	   data	    bss	    dec	    hex	filename
 950034	    477	   7296	 957807	  e9d6f	busybox_old
 949918	    477	   7296	 957691	  e9cfb	busybox_unstripped

Signed-off-by: Ron Yorston <rmy@pobox.com>
Signed-off-by: Denys Vlasenko <vda.linux@googlemail.com>

diff --git a/scripts/embedded_scripts b/scripts/embedded_scripts
--- a/scripts/embedded_scripts
+++ b/scripts/embedded_scripts
@@ -1,7 +1,8 @@
 #!/bin/sh
 
 target="$1"
-loc="$2"
+custom_loc="$2"
+applet_loc="$3"
 
 test "$target" || exit 1
 test "$SED" || SED=sed
@@ -14,46 +15,102 @@ if test $? != 0; then
 	exit 1
 fi
 
-exec >"$target.$$"
-
-scripts=""
-if [ -d "$loc" ]
+custom_scripts=""
+if [ -d "$custom_loc" ]
 then
-	scripts=$(cd $loc; ls * 2>/dev/null)
+	custom_scripts=$(cd $custom_loc; ls * 2>/dev/null)
+fi
+all_scripts=$(applets/busybox.mkscripts)
+
+# all_scripts includes applet scripts and custom scripts, sort them out
+applet_scripts=""
+for i in $all_scripts
+do
+    found=0
+	for j in $custom_scripts
+	do
+		if [ "$i" = "$j" ]
+		then
+			found=1
+			break;
+		fi
+	done
+	if [ $found -eq 0 ]
+	then
+		# anything that isn't a custom script is an applet script
+		applet_scripts="$applet_scripts $i"
+	fi
+done
+
+# we know the custom scripts are present but applet scripts might have
+# become detached from their configuration
+for i in $applet_scripts
+do
+	#if [ ! -f "$applet_loc/$i" -a ! -f "$custom_loc/$i" ]
+	if [ ! -f "$applet_loc/$i" ]
+	then
+		echo "missing applet script $i"
+		exit 1
+	fi
+done
+
+n=$(echo $custom_scripts $applet_scripts | wc -w)
+nall=$(echo $all_scripts | wc -w)
+
+if [ $n -ne $nall ]
+then
+	echo "script mismatch $n != $nall"
+	exit 1
 fi
 
-n=$(echo $scripts | wc -w)
+concatenate_scripts() {
+	for i in $custom_scripts
+	do
+		cat $custom_loc/$i
+		printf '\000'
+	done
+	for i in $applet_scripts
+	do
+		cat $applet_loc/$i
+		printf '\000'
+	done
+}
+
+exec >"$target.$$"
 
 if [ $n -ne 0 ]
 then
-	printf '#ifdef DEFINE_script_names\n'
-	printf 'const char script_names[] ALIGN1 = '
-	for i in $scripts
-	do
-		printf '"%s\\0"' $i
-	done
-	printf ';\n'
+	printf '#ifdef DEFINE_SCRIPT_DATA\n'
+	if [ $n -ne 0 ]
+	then
+		printf 'const uint16_t applet_numbers[] = {\n'
+		for i in $custom_scripts $applet_scripts
+		do
+			# TODO support applets with names including invalid characters
+			printf '\tAPPLET_NO_%s,\n' $i
+		done
+		printf '};\n'
+	fi
 	printf '#else\n'
-	printf 'extern const char script_names[] ALIGN1;\n'
+	if [ $n -ne 0 ]
+	then
+		printf 'extern const uint16_t applet_numbers[];\n'
+	fi
 	printf '#endif\n'
 fi
-printf "#define NUM_SCRIPTS $n\n\n"
+
+printf "\n"
+printf '#define NUM_SCRIPTS %d\n' $n
+printf "\n"
 
 if [ $n -ne 0 ]
 then
 	printf '#define UNPACKED_SCRIPTS_LENGTH '
-	for i in $scripts
-	do
-		cat $loc/$i
-		printf '\000'
-	done | wc -c
+	concatenate_scripts | wc -c
 
 	printf '#define PACKED_SCRIPTS \\\n'
-	for i in $scripts
-	do
-		cat $loc/$i
-		printf '\000'
-	done | bzip2 -1 | $DD bs=2 skip=1 2>/dev/null | od -v -b \
+	concatenate_scripts | bzip2 -1 | $DD bs=2 skip=1 2>/dev/null | \
+	od -v -b \
 	| grep -v '^ ' \
 	| $SED -e 's/^[^ ]*//' \
 		-e 's/ //g' \
